import { useState } from 'react'
import { CheckCircle, AlertCircle, Clock, Sparkles, ChevronLeft, ChevronRight } from 'lucide-react'
import { dailySummaries } from '../data/mockData'

interface AISummariesProps { isDark: boolean }

export default function AISummaries({ isDark }: AISummariesProps) {
  const [idx, setIdx] = useState(0)
  const summary = dailySummaries[idx]

  const surface = isDark ? '#111111' : '#ffffff'
  const border = isDark ? '#1f1f1f' : '#e5e7eb'
  const textPrimary = isDark ? '#fafafa' : '#111827'
  const textSecondary = isDark ? '#a3a3a3' : '#6b7280'
  const textMuted = isDark ? '#525252' : '#9ca3af'
  const formatDate = (d: string) =>
    new Date(d).toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })

  return (
    <div style={{ maxWidth: '860px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <div>
          <h1 style={{ fontSize: '22px', fontWeight: 700, color: textPrimary, marginBottom: '4px', letterSpacing: '-0.3px' }}>
            AI Summaries
          </h1>
          <p style={{ fontSize: '13px', color: textSecondary }}>
            Auto-generated end-of-day operational reports
          </p>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <button
            onClick={() => setIdx(Math.min(dailySummaries.length - 1, idx + 1))}
            disabled={idx >= dailySummaries.length - 1}
            style={{
              padding: '6px', border: `1px solid ${border}`, borderRadius: '7px',
              background: 'none', cursor: 'pointer',
              color: idx >= dailySummaries.length - 1 ? textMuted : textSecondary,
            }}
          >
            <ChevronLeft size={14} />
          </button>
          <span style={{ fontSize: '13px', color: textSecondary, minWidth: '180px', textAlign: 'center' }}>
            {formatDate(summary.date)}
          </span>
          <button
            onClick={() => setIdx(Math.max(0, idx - 1))}
            disabled={idx === 0}
            style={{
              padding: '6px', border: `1px solid ${border}`, borderRadius: '7px',
              background: 'none', cursor: 'pointer',
              color: idx === 0 ? textMuted : textSecondary,
            }}
          >
            <ChevronRight size={14} />
          </button>
        </div>
      </div>

      {/* AI label */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: '8px',
        marginBottom: '16px',
        padding: '10px 16px', borderRadius: '10px',
        backgroundColor: isDark ? 'rgba(99,102,241,0.08)' : '#f0f4ff',
        border: `1px solid ${isDark ? 'rgba(99,102,241,0.2)' : '#c7d2fe'}`,
      }}>
        <Sparkles size={14} color="#6366f1" />
        <span style={{ fontSize: '12.5px', color: isDark ? '#818cf8' : '#4f46e5', fontWeight: 500 }}>
          Generated by Workspace AI · {new Date(summary.generatedAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>

      {/* Stats row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', marginBottom: '20px' }}>
        {[
          { label: 'Tasks Completed', value: summary.completedTasks, color: '#22c55e', icon: CheckCircle },
          { label: 'Tasks Blocked', value: summary.blockedTasks, color: '#ef4444', icon: AlertCircle },
          { label: 'Tasks Pending', value: summary.pendingTasks, color: '#f59e0b', icon: Clock },
        ].map(({ label, value, color, icon: Icon }) => (
          <div key={label} style={{
            backgroundColor: surface, border: `1px solid ${border}`,
            borderRadius: '12px', padding: '18px 20px',
            display: 'flex', alignItems: 'center', gap: '14px',
          }}>
            <div style={{
              width: '40px', height: '40px', borderRadius: '10px',
              backgroundColor: color + (isDark ? '18' : '18'),
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Icon size={18} color={color} />
            </div>
            <div>
              <div style={{ fontSize: '26px', fontWeight: 800, color, lineHeight: 1, letterSpacing: '-0.5px' }}>
                {value}
              </div>
              <div style={{ fontSize: '12px', color: textMuted, marginTop: '3px' }}>{label}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Highlights */}
      <div style={{
        backgroundColor: surface, border: `1px solid ${border}`,
        borderRadius: '12px', padding: '20px', marginBottom: '12px',
      }}>
        <div style={{ fontSize: '14px', fontWeight: 600, color: textPrimary, marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <CheckCircle size={15} color="#22c55e" />
          Highlights
        </div>
        <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {summary.highlights.map((h, i) => (
            <li key={i} style={{
              display: 'flex', gap: '10px', alignItems: 'flex-start',
              fontSize: '13.5px', color: textSecondary, lineHeight: '1.5',
            }}>
              <span style={{ color: '#22c55e', marginTop: '2px', flexShrink: 0 }}>✓</span>
              {h}
            </li>
          ))}
        </ul>
      </div>

      {/* Blockers */}
      {summary.blockers.length > 0 && (
        <div style={{
          backgroundColor: surface, border: `1px solid ${border}`,
          borderRadius: '12px', padding: '20px', marginBottom: '12px',
        }}>
          <div style={{ fontSize: '14px', fontWeight: 600, color: textPrimary, marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <AlertCircle size={15} color="#ef4444" />
            Blockers
          </div>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {summary.blockers.map((b, i) => (
              <li key={i} style={{
                display: 'flex', gap: '10px', alignItems: 'flex-start',
                fontSize: '13.5px', color: textSecondary, lineHeight: '1.5',
              }}>
                <span style={{ color: '#ef4444', marginTop: '2px', flexShrink: 0 }}>!</span>
                {b}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Next day priorities */}
      <div style={{
        backgroundColor: surface, border: `1px solid ${border}`,
        borderRadius: '12px', padding: '20px',
      }}>
        <div style={{ fontSize: '14px', fontWeight: 600, color: textPrimary, marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Clock size={15} color="#3b82f6" />
          Tomorrow's Priorities
        </div>
        <ol style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {summary.nextDayPriorities.map((p, i) => (
            <li key={i} style={{
              display: 'flex', gap: '10px', alignItems: 'flex-start',
              fontSize: '13.5px', color: textSecondary, lineHeight: '1.5',
            }}>
              <span style={{
                minWidth: '20px', height: '20px', borderRadius: '50%',
                backgroundColor: isDark ? '#1f1f1f' : '#f3f4f6',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: '10.5px', fontWeight: 700, color: '#3b82f6',
                flexShrink: 0, marginTop: '1px',
              }}>{i + 1}</span>
              {p}
            </li>
          ))}
        </ol>
      </div>
    </div>
  )
}
